// Lifecycle
export const INIT = 'INIT'

// Chapters
export const NEXT_CHAPTER = 'NEXT_CHAPTER'
export const SET_NEXT_CHAPTER = 'SET_NEXT_CHAPTER'
export const PREVIOUS_CHAPTER = 'PREVIOUS_CHAPTER'
export const SET_PREVIOUS_CHAPTER = 'SET_PREVIOUS_CHAPTER'
export const SET_CHAPTER = 'SET_CHAPTER'
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER'
export const INIT_CHAPTERS = 'INIT_CHAPTERS'

// Components
export const TOGGLE_COMPONENT_INFO = 'TOGGLE_COMPONENT_INFO'
export const TOGGLE_COMPONENT_INFO_POSTER = 'TOGGLE_COMPONENT_INFO_POSTER'
export const TOGGLE_COMPONENT_ERROR = 'TOGGLE_COMPONENT_ERROR'
export const TOGGLE_COMPONENT_CONTROLS_CHAPTERS = 'TOGGLE_COMPONENT_CONTROLS_CHAPTERS'
export const TOGGLE_COMPONENT_CONTROLS_STEPPERS = 'TOGGLE_COMPONENT_CONTROLS_STEPPERS'
export const SHOW_COMPONENT_CONTROLS_BUTTON_LOADING = 'SHOW_COMPONENT_CONTROLS_BUTTON_LOADING'
export const SHOW_COMPONENT_CONTROLS_BUTTON_REPLAY = 'SHOW_COMPONENT_CONTROLS_BUTTON_REPLAY'
export const SHOW_COMPONENT_CONTROLS_BUTTON_REMAINING = 'SHOW_COMPONENT_CONTROLS_BUTTON_REMAINING'
export const SHOW_COMPONENT_CONTROLS_BUTTON_DURATION = 'SHOW_COMPONENT_CONTROLS_BUTTON_DURATION'
export const SHOW_COMPONENT_CONTROLS_BUTTON_RETRY = 'SHOW_COMPONENT_CONTROLS_BUTTON_RETRY'
export const SHOW_COMPONENT_CONTROLS_BUTTON_PLAYING = 'SHOW_COMPONENT_CONTROLS_BUTTON_PLAYING'
export const SHOW_COMPONENT_CONTROLS_BUTTON_PAUSE = 'SHOW_COMPONENT_CONTROLS_BUTTON_PAUSE'
export const TOGGLE_COMPONENT_TAB = 'TOGGLE_COMPONENT_TAB'
export const TOGGLE_COMPONENT_VOLUME_SLIDER = 'TOGGLE_COMPONENT_VOLUME_SLIDER'
export const TOGGLE_COMPONENT_RATE_SLIDER = 'TOGGLE_COMPONENT_RATE_SLIDER'
export const TOGGLE_COMPONENT_PROGRESSBAR = 'TOGGLE_COMPONENT_PROGRESSBAR'
export const TOGGLE_COMPONENT_CONTROLS_BUTTON = 'TOGGLE_COMPONENT_CONTROLS_BUTTON'

// Download
export const SET_DOWNLOAD_FILE = 'SET_DOWNLOAD_FILE'

// Error
export const ERROR_LOAD = 'ERROR_LOAD'
export const NETWORK_EMPTY = 'NETWORK_EMPTY'
export const NETWORK_NO_SOURCE = 'NETWORK_NO_SOURCE'
export const ERROR_MISSING_AUDIO_FILES = 'ERROR_MISSING_AUDIO_FILES'

// Ghost
export const SIMULATE_PLAYTIME = 'SIMULATE_PLAYTIME'
export const ENABLE_GHOST_MODE = 'ENABLE_GHOST_MODE'
export const DISABLE_GHOST_MODE = 'DISABLE_GHOST_MODE'

// Player
export const SET_DURATION = 'SET_DURATION'
export const SET_BUFFER = 'SET_BUFFER'
export const PLAY = 'PLAY'
export const UI_PLAY = 'UI_PLAY'
export const PAUSE = 'PAUSE'
export const UI_PAUSE = 'UI_PAUSE'
export const STOP = 'STOP'
export const IDLE = 'IDLE'
export const UI_RESTART = 'UI_RESTART'
export const LOADING = 'LOADING'
export const LOAD = 'LOAD'
export const LOADED = 'LOADED'
export const END = 'END'

// Audio
export const MUTE = 'MUTE'
export const UNMUTE = 'UNMUTE'
export const SET_VOLUME = 'SET_VOLUME'
export const SET_RATE = 'SET_RATE'

// Playtime
export const SET_PLAYTIME = 'SET_PLAYTIME'
export const UPDATE_PLAYTIME = 'UPDATE_PLAYTIME'

// Quantiles
export const LOAD_QUANTILES = 'LOAD_QUANTILES'
export const SET_QUANTILE = 'SET_QUANTILE'

// Runtime
export const SET_LANGUAGE = 'SET_LANGUAGE'

// Share
export const SET_SHARE_CONTENT = 'SET_SHARE_CONTENT'
export const SET_SHARE_EMBED_SIZE = 'SET_SHARE_EMBED_SIZE'
export const SHOW_SHARE_EMBED = 'SHOW_SHARE_EMBED'
export const HIDE_SHARE_EMBED = 'HIDE_SHARE_EMBED'

// Tabs
export const TOGGLE_TAB = 'TOGGLE_TAB'
export const SET_TABS = 'SET_TABS'

// Theme
export const SET_THEME = 'SET_THEME'

// Transcripts
export const INIT_TRANSCRIPTS = 'INIT_TRANSCRIPTS'
export const SET_TRANSCRIPTS_TIMELINE = 'SET_TRANSCRIPTS_TIMELINE'
export const SET_TRANSCRIPTS_CHAPTERS = 'SET_TRANSCRIPTS_CHAPTERS'
export const UPDATE_TRANSCRIPTS = 'UPDATE_TRANSCRIPTS'
export const TOGGLE_FOLLOW_TRANSCRIPTS = 'TOGGLE_FOLLOW_TRANSCRIPTS'
export const SEARCH_TRANSCRIPTS = 'SEARCH_TRANSCRIPTS'
export const SET_SEARCH_TRANSCRIPTS_RESULTS = 'SET_SEARCH_TRANSCRIPTS_RESULTS'
export const NEXT_SEARCH_RESULT = 'NEXT_SEARCH_RESULT'
export const PREVIOUS_SEARCH_RESULT = 'PREVIOUS_SEARCH_RESULT'
export const RESET_SEARCH_TRANSCRIPTS = 'RESET_SEARCH_TRANSCRIPTS'

// Restore
export const SET_PLAYBACK_PARAMS = 'SET_PLAYBACK_PARAMS'
