export default {
  defaultVideoWidth: -1,
  defaultVideoHeight: -1,
  videoWidth: -1,
  videoHeight: -1,
  audioWidth: -1,
  audioHeight: -1,
  startVolume: 0.8,
  loop: false,
  enableAutosize: true,
  features: ['playpause', 'current', 'progress', 'duration', 'tracks', 'fullscreen'],
  alwaysShowControls: false,
  iPadUseNativeControls: false,
  iPhoneUseNativeControls: false,
  AndroidUseNativeControls: false,
  alwaysShowHours: false,
  showTimecodeFrameCount: false,
  framesPerSecond: 1,
  enableKeyboard: true,
  pauseOtherPlayers: true,
  duration: false,
  plugins: ['flash', 'silverlight'],
  pluginPath: './bin/',
  flashName: 'flashmediaelement.swf',
  silverlightName: 'silverlightmediaelement.xap'
}
